### ISSUE TITLE
[Bug] tags are not saved

### ISSUE THREAD

**Issue by hanckmann** [damko/freedommarks-browser-webextension#9]
Using this extension in Firefox 59.0.2 64 bit on Linux (Arch Linux), the tags are not stored on the nextcloud server.

Furthermore, it is unclear how multiple tags need to be added (if it would work); should we separate tags with commas? Does it support multi-word tags? Of do we need to encapsulate those words in quotes?

**Comment by damko** [comment]
hello, yes tags are not stored because nextcloud 13 bookmarks app has changed something in the api and broke the extension. Known bug but I didn't have yet the time to look into it.

Yes it supports multiple tags, separated by commas therefore multiple words would work as one tag. No quotes required, the comma is the limit field
